import express from 'express'
import cors from 'cors'
import { seedLoans, audit } from './data.js'
import { verifyLoan } from './verification.js'

const app = express(); const loans = structuredClone(seedLoans); let auditLog = structuredClone(audit)
app.use(cors()); app.use(express.json({ limit: '1mb' }))
const enrich = loan => ({ ...loan, verification: verifyLoan(loan), audit: auditLog.filter(a => a.loanId === loan.id) })
app.get('/api/health', (_, res) => res.json({ ok: true, time: new Date().toISOString() }))
app.get('/api/dashboard', (_, res) => { const records = loans.map(enrich); res.json({ metrics: { total: records.length, verified: records.filter(r => r.verification.status === 'verified').length, attention: records.filter(r => ['attention','exception'].includes(r.verification.status)).length, review: records.filter(r => r.verification.status === 'review').length }, recentActivity: auditLog.slice(0, 5), records }) })
app.get('/api/loans', (req, res) => { const q = String(req.query.q || '').toLowerCase(); const status = req.query.status; let records = loans.map(enrich); if(q) records = records.filter(r => `${r.id} ${r.borrower} ${r.product}`.toLowerCase().includes(q)); if(status && status !== 'all') records = records.filter(r => r.verification.status === status); res.json(records) })
app.get('/api/loans/:id', (req, res) => { const loan = loans.find(x => x.id === req.params.id); if (!loan) return res.status(404).json({ message: 'Loan record not found.' }); res.json(enrich(loan)) })
app.post('/api/loans', (req, res) => { const b = req.body; if (!b.borrower?.trim() || !b.product || !Number(b.amount)) return res.status(400).json({ message: 'Borrower name, product and requested amount are required.' }); const id = `LN-2026-${String(486 + loans.length).padStart(5,'0')}`; const loan = { id, borrower: b.borrower.trim(), product: b.product, amount: Number(b.amount), income: Number(b.income)||0, employment: b.employment || 'Salaried', bureauScore: Number(b.bureauScore)||0, declaredObligation: Number(b.declaredObligation)||0, calculatedEmi: Number(b.calculatedEmi)||0, propertyValue: Number(b.propertyValue)||null, pan: String(b.pan||'').toUpperCase(), bankVerified: Boolean(b.bankVerified), documents: b.documents || [], status: 'review', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), reviewer: null }; loans.unshift(loan); auditLog.unshift({ id: Date.now(), loanId:id, action:'Loan data ingested and verification triggered', actor:'Operations user', at:new Date().toISOString() }); res.status(201).json(enrich(loan)) })
app.post('/api/loans/:id/action', (req,res) => { const loan = loans.find(x=>x.id===req.params.id); const { action, note='' } = req.body; if(!loan) return res.status(404).json({message:'Loan record not found.'}); if(!['approve','review','reject'].includes(action)) return res.status(400).json({message:'Unsupported action.'}); loan.status = action === 'approve' ? 'verified' : action === 'reject' ? 'exception' : 'review'; loan.reviewer='Operations user'; loan.updatedAt = new Date().toISOString(); auditLog.unshift({id:Date.now(),loanId:loan.id,action:`${action === 'approve' ? 'Approved' : action === 'reject' ? 'Rejected' : 'Sent for review'}${note ? `: ${note}` : ''}`,actor:'Operations user',at:loan.updatedAt}); res.json(enrich(loan)) })
app.use((err,_,res,__)=> { console.error(err); res.status(500).json({ message:'Unexpected server error. Please try again.' }) })
app.listen(4000, () => console.log('Loan verification API running at http://localhost:4000'))
