import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { AlertTriangle, ArrowLeft, CheckCircle2, ChevronRight, CircleHelp, ClipboardCheck, FilePlus2, LayoutDashboard, RefreshCw, Search, ShieldCheck, Upload, X, Clock3 } from 'lucide-react'
import './styles.css'

const api = async (path, options) => { const r = await fetch(`/api${path}`, { headers: { 'Content-Type': 'application/json' }, ...options }); const data = await r.json(); if (!r.ok) throw new Error(data.message || 'Something went wrong'); return data }
const money = v => `₹${Number(v || 0).toLocaleString('en-IN')}`
const label = s => ({ verified:'Verified', attention:'Attention', exception:'Exception', review:'In review' })[s] || s

function App() {
  const [page, setPage] = useState('dashboard'), [records, setRecords] = useState([]), [metrics, setMetrics] = useState(null), [selected, setSelected] = useState(null), [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [loading, setLoading] = useState(true), [error, setError] = useState(''), [toast, setToast] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const data = await api('/dashboard'); setRecords(data.records); setMetrics(data.metrics) } catch(e) { setError(e.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const filtered = useMemo(() => records.filter(r => (!search || `${r.id} ${r.borrower} ${r.product}`.toLowerCase().includes(search.toLowerCase())) && (filter === 'all' || r.verification.status === filter)), [records, search, filter])
  const open = async (id) => { try { setSelected(await api(`/loans/${id}`)); setPage('detail') } catch(e) { setToast(e.message) } }
  const action = async (a) => { try { const fresh = await api(`/loans/${selected.id}/action`, { method:'POST', body:JSON.stringify({action:a}) }); setSelected(fresh); setToast(`Record ${a === 'approve' ? 'approved' : a === 'reject' ? 'rejected' : 'sent for review'}.`); await load() } catch(e) { setToast(e.message) } }
  return <div className="app"><aside><div className="brand"><span className="brandmark"><ShieldCheck size={21}/></span><span>Verity<span className="branddot">.</span></span></div><div className="workspace">WORKSPACE</div><nav><button className={page==='dashboard'?'active':''} onClick={()=>setPage('dashboard')}><LayoutDashboard/>Overview</button><button className={page==='loans'||page==='detail'?'active':''} onClick={()=>setPage('loans')}><ClipboardCheck/>Verification queue</button><button className={page==='upload'?'active':''} onClick={()=>setPage('upload')}><FilePlus2/>New verification</button></nav><div className="sidebar-bottom"><div className="security"><ShieldCheck size={17}/><span><b>Secure workspace</b><small>Audit logging enabled</small></span></div><div className="avatar">OS</div><span className="user-name">Operations<br/><small>Analyst</small></span></div></aside><main><header><div>{page==='dashboard' ? <><p className="eyebrow">TUESDAY, 26 AUGUST 2026</p><h1>Good morning, Operations.</h1></> : <><button className="back" onClick={()=>setPage('loans')}><ArrowLeft size={17}/> Back to queue</button><h1>{page==='upload'?'Start a verification': selected ? selected.id : 'Verification queue'}</h1></>}</div><div className="header-right"><button className="icon-btn" title="Help"><CircleHelp size={20}/></button><button className="primary" onClick={()=>setPage('upload')}><FilePlus2 size={17}/> New verification</button></div></header>{toast && <div className="toast"><CheckCircle2 size={18}/>{toast}<button onClick={()=>setToast('')}><X size={16}/></button></div>}{error && <div className="error"><AlertTriangle size={18}/><span>{error}</span><button onClick={load}><RefreshCw size={15}/>Retry</button></div>}{loading ? <Loading/> : page==='dashboard' ? <Dashboard metrics={metrics} records={records} open={open} setPage={setPage}/> : page==='loans' ? <Queue records={filtered} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} open={open}/> : page==='detail' && selected ? <Detail record={selected} action={action}/> : <NewLoan done={async record => { setToast(`${record.id} created and checked.`); await load(); setSelected(record); setPage('detail') }}/>}</main></div>
}
function Loading(){ return <div className="loading"><RefreshCw className="spin"/><p>Loading verification workspace…</p></div> }
function Status({status}){ return <span className={`status ${status}`}><i/>{label(status)}</span> }
function Dashboard({metrics, records, open, setPage}) { return <><section className="metrics"><Metric title="Applications in queue" value={metrics.total} icon={<ClipboardCheck/>} tone="blue"/><Metric title="Verified automatically" value={metrics.verified} icon={<CheckCircle2/>} tone="green"/><Metric title="Need attention" value={metrics.attention} icon={<AlertTriangle/>} tone="amber"/><Metric title="Awaiting review" value={metrics.review} icon={<Clock3/>} tone="purple"/></section><section className="split"><div className="panel"><div className="panel-head"><div><h2>Priority exceptions</h2><p>Items requiring an analyst decision</p></div><button className="text-btn" onClick={()=>setPage('loans')}>View queue <ChevronRight size={16}/></button></div><div className="exception-list">{records.filter(x=>x.verification.status!=='verified').slice(0,3).map(r=><button className="exception" key={r.id} onClick={()=>open(r.id)}><span className={`severity ${r.verification.issues[0]?.severity||'medium'}`}><AlertTriangle size={18}/></span><span><b>{r.borrower}</b><small>{r.id} · {r.verification.issues[0]?.title || 'Manual review requested'}</small></span><Status status={r.verification.status}/><ChevronRight size={17}/></button>)}</div></div><div className="panel readiness"><div className="panel-head"><div><h2>Portfolio readiness</h2><p>Today’s verification outcomes</p></div></div><div className="ring"><span><b>{Math.round(metrics.verified/metrics.total*100)}%</b><small>verified</small></span></div><div className="legend"><span><i className="green"/>Verified <b>{metrics.verified}</b></span><span><i className="amber"/>Attention <b>{metrics.attention}</b></span><span><i className="purple"/>Review <b>{metrics.review}</b></span></div></div></section><section className="panel table-panel"><div className="panel-head"><div><h2>Recent applications</h2><p>Latest records processed by Verity</p></div><button className="text-btn" onClick={()=>setPage('loans')}>Open all <ChevronRight size={16}/></button></div><RecordTable records={records.slice(0,5)} open={open}/></section></> }
function Metric({title,value,icon,tone}){return <div className="metric"><span className={`metric-icon ${tone}`}>{icon}</span><div><p>{title}</p><h2>{value}</h2><small>{tone==='green'?'No critical exceptions':'Updated just now'}</small></div></div>}
function Queue({records,search,setSearch,filter,setFilter,open}) { return <section className="panel queue"><div className="queue-top"><div><h2>Verification queue</h2><p>Review data quality signals and route applications confidently.</p></div></div><div className="filters"><label><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search application or borrower"/></label><div className="filter-tabs">{['all','attention','exception','review','verified'].map(s=><button key={s} onClick={()=>setFilter(s)} className={filter===s?'selected':''}>{s==='all'?'All records':label(s)}</button>)}</div></div>{records.length ? <RecordTable records={records} open={open}/> : <div className="empty"><Search size={28}/><h3>No matching records</h3><p>Try clearing your search or changing the status filter.</p></div>}</section>}
function RecordTable({records,open}){return <div className="table-wrap"><table><thead><tr><th>Application</th><th>Product</th><th>Requested amount</th><th>Risk signals</th><th>Verification</th><th></th></tr></thead><tbody>{records.map(r=><tr key={r.id} onClick={()=>open(r.id)}><td><b>{r.borrower}</b><small>{r.id}</small></td><td>{r.product}</td><td>{money(r.amount)}</td><td><span className={r.verification.issues.length?'signal warn':'signal good'}>{r.verification.issues.length ? `${r.verification.issues.length} issue${r.verification.issues.length>1?'s':''}`:'Clear'}</span></td><td><Status status={r.verification.status}/></td><td><ChevronRight size={18}/></td></tr>)}</tbody></table></div>}
function Detail({record,action}){const v=record.verification; return <><section className="detail-head"><div><div className="detail-title"><h2>{record.borrower}</h2><Status status={v.status}/></div><p>{record.product} · {record.id} · Submitted {new Date(record.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</p></div><div className="actions"><button className="secondary" onClick={()=>action('review')}>Send to review</button><button className="danger" onClick={()=>action('reject')}>Reject</button><button className="primary" onClick={()=>action('approve')}><CheckCircle2 size={17}/>Approve record</button></div></section><section className="detail-grid"><div><div className="panel verification-card"><div className="verification-score"><div className={`score ${v.score>70?'good':v.score>40?'warn':'bad'}`}>{v.score}<small>/100</small></div><div><p className="eyebrow">VERIFICATION CONFIDENCE</p><h2>{v.status==='verified'?'Ready to progress':v.status==='exception'?'Blocking exceptions found':'Analyst attention required'}</h2><p>{v.issues.length ? `${v.issues.length} validation signal${v.issues.length>1?'s':''} detected across applicant data.`:'All automated data checks passed.'}</p></div></div><h3>Verification findings</h3>{v.issues.length ? <div className="findings">{v.issues.map(x=><div className="finding" key={x.id}><span className={`severity ${x.severity}`}><AlertTriangle size={17}/></span><div><b>{x.title}</b><p>{x.description}</p><small>{x.severity.toUpperCase()} · {x.field}</small></div></div>)}</div> : <div className="all-clear"><CheckCircle2/><div><b>All policy checks passed</b><p>This record is complete, internally consistent, and eligible for straight-through processing.</p></div></div>}</div></div><div className="panel"><h3>Application snapshot</h3><dl><dt>Requested amount</dt><dd>{money(record.amount)}</dd><dt>Monthly income</dt><dd>{money(record.income)}</dd><dt>Employment</dt><dd>{record.employment}</dd><dt>Bureau score</dt><dd>{record.bureauScore || 'Not provided'}</dd><dt>FOIR</dt><dd>{v.metrics.foir}%</dd><dt>Property value</dt><dd>{record.propertyValue?money(record.propertyValue):'Not provided'}</dd></dl><hr/><h3>Evidence received</h3><div className="chips">{record.documents.length?record.documents.map(x=><span key={x}>{x}</span>):<span>No documents</span>}</div></div></section><section className="panel audit"><h3>Audit trail</h3>{record.audit.length?record.audit.map(a=><div className="audit-row" key={a.id}><span><Clock3 size={16}/></span><div><b>{a.action}</b><p>{a.actor} · {new Date(a.at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</p></div></div>):<p className="muted">No review actions recorded yet.</p>}</section></>}
function NewLoan({done}){const [form,setForm]=useState({ borrower:'',product:'Home Loan',amount:'',income:'',employment:'Salaried',bureauScore:'',declaredObligation:'',calculatedEmi:'',propertyValue:'',pan:'',bankVerified:false,documents:[] }); const [submitting,setSubmitting]=useState(false), [err,setErr]=useState(''); const change=e=>setForm({...form,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}); const submit=async e=>{e.preventDefault();setSubmitting(true);setErr('');try{done(await api('/loans',{method:'POST',body:JSON.stringify(form)}))}catch(x){setErr(x.message)}finally{setSubmitting(false)}}; return <section className="form-page"><div className="form-intro"><span className="intro-icon"><Upload/></span><div><h2>Ingest loan application data</h2><p>Enter application details to run policy, completeness and consistency checks in real time.</p></div></div>{err&&<div className="error"><AlertTriangle size={18}/>{err}</div>}<form className="panel form" onSubmit={submit}><h3>Applicant details</h3><div className="form-grid"><Field label="Borrower full name *" name="borrower" value={form.borrower} onChange={change} placeholder="e.g. Kavya Nair"/><Select label="Loan product *" name="product" value={form.product} onChange={change} options={['Home Loan','Personal Loan','Business Loan','Auto Loan']}/><Field label="PAN" name="pan" value={form.pan} onChange={change} placeholder="ABCDE1234F"/><Select label="Employment type" name="employment" value={form.employment} onChange={change} options={['Salaried','Self-employed','Business owner']}/></div><h3>Financial and verification data</h3><div className="form-grid"><Field label="Requested amount (₹) *" type="number" name="amount" value={form.amount} onChange={change}/><Field label="Monthly income (₹)" type="number" name="income" value={form.income} onChange={change}/><Field label="Bureau score" type="number" name="bureauScore" value={form.bureauScore} onChange={change}/><Field label="Declared monthly obligations (₹)" type="number" name="declaredObligation" value={form.declaredObligation} onChange={change}/><Field label="Assessed EMI (₹)" type="number" name="calculatedEmi" value={form.calculatedEmi} onChange={change}/><Field label="Property value (₹, home loan only)" type="number" name="propertyValue" value={form.propertyValue} onChange={change}/></div><label className="check"><input type="checkbox" name="bankVerified" checked={form.bankVerified} onChange={change}/><span/><div><b>Bank statement verified</b><small>I confirm income and banking evidence have been received and checked.</small></div></label><div className="form-foot"><p>Verification runs automatically on submission.</p><button disabled={submitting} className="primary" type="submit">{submitting?<><RefreshCw className="spin" size={17}/>Running checks…</>:<><ShieldCheck size={17}/>Create & verify</>}</button></div></form></section>}
function Field(p){return <label className="field"><span>{p.label}</span><input {...p}/></label>} function Select({label,...p}){return <label className="field"><span>{label}</span><select {...p}>{p.options.map(x=><option key={x}>{x}</option>)}</select></label>}
createRoot(document.getElementById('root')).render(<App />)
